### ISSUE TITLE
Click the api and web url fails for todo-java-postgresql-terraform

### ISSUE THREAD

**Issue by Menghua1** [fangjian0423/todo-java-postgresql-terraform#1]
**Describe the issue:**
When executing command `azd up --template https://github.com/fangjian0423/todo-java-postgresql-terraform -l "eastus"`, all services are deployed successfully in output. But, when open the web and api url, there are some errors.
- Opening the web url, the page keeps loading. The detailed error is as follows:
![image](https://user-images.githubusercontent.com/111940661/218028587-e6a0d937-a6bc-4394-82e3-0e22d28160fa.png)
- Opening the api url, there is an application error. The detailed error is as follows:
![image](https://user-images.githubusercontent.com/111940661/218028899-05e73108-7fae-43a1-84df-d5e3cb77364a.png)

**Repro Steps:**
1.Run task `azd up --template https://github.com/fangjian0423/todo-java-postgresql-terraform`

2.Click the web and api url.

**Environment:**
- OS: windows .
- Template: https://github.com/fangjian0423/todo-java-postgresql-terraform 
- Branch: main.
- Azd version: azd version 0.6.0-beta.2-daily.2174213 (commit 0ba86fb89023d4d52377211473de8286ee9df028)

**Expected behavior:**
Click the api and web url success.

@fangjian0423 for notification.

**Comment by fangjian0423** [comment]
I guess the `local-exec` execute failed, did you install the [PostgreSQL](https://www.postgresql.org/) as Prerequisites described @Menghua1

**Comment by fangjian0423** [comment]
The problem resolved after PostgreSQL installed, cc @Menghua1

**Comment by v-xuto** [comment]
@fangjian0423 Can you add a relevant hint on the README about PostgreSQL?
- After PostgreSQL10.5 is installed, environment variables need to be configured, such as `C:\PostgreSQL10\bin`.
- Use the `psql` command to connect to the database to see if it can connect to the database normally?

**Comment by fangjian0423** [comment]
@v-xuto

Done.
![image](https://user-images.githubusercontent.com/5254035/218700460-9c8b0bb2-9a79-4d5f-b6a8-10b4f84d103d.png)
