### ISSUE TITLE
 Executing command "azd pipeline config" failed. 

### ISSUE THREAD

**Issue by Menghua1** [fangjian0423/todo-java-postgresql-terraform#2]
**Describe the issue:**
When executing command `azd pipeline config`, an error is reported in the github pipeline that `azd is not logged in`. 
The detailed error is as follows:
![image](https://user-images.githubusercontent.com/111940661/218963631-1b3e3c8f-cd9c-4548-869f-5ad1c48f683a.png)

**Repro Steps:**
1.Execute command `azd up --template https://github.com/fangjian0423/todo-java-postgresql-terraform -l "eastus" `.

2.Run: `azd pipeline config`.

3.Click on the link that is printed to open the actions page. 

**Environment:**
- OS: windows .
- Template: https://github.com/fangjian0423/todo-java-postgresql-terraform
- Branch: main.
- Azd version: azd version 0.6.0-beta.3-daily.2185344 (commit d74ef73e28a1e6f8b0e2045cc8a40d4f9f0a42af)

**Expected behavior:**
Action logs can pass successfully.

@fangjian0423 for notification.

**Comment by fangjian0423** [comment]
hi @Menghua1 , the issue you created has been fixed, but will meet a new issue when you retry it:

```bash
╷
│ Error: A resource with the ID "/subscriptions/***/resourceGroups/rg-***" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_resource_group" for more information.
│ 
│   with azurerm_resource_group.rg,
│   on main.tf line 18, in resource "azurerm_resource_group" "rg":
│   18: resource "azurerm_resource_group" "rg" {
│ 
╵
```

You will meet the same problem when you test with https://github.com/Azure-Samples/todo-python-mongo-terraform template. 

I think current test step for terraform template is not correct.

Current test step:

1. run `azd up` with target template (**will create azure resource but not sync to remote state file**)
2. follow https://aka.ms/azure-dev/terraform to enable remote state
3. run `azd pipeline config`
4. check Github Action

I think the ideal step is:

1. run `azd init` to get the target template
2. follow https://aka.ms/azure-dev/terraform to enable remote state
3. run `azd pipeline config`
4. check Github Action

how do you think about it? @v-xuto @Menghua1

**Comment by fangjian0423** [comment]
I find that terraform template should run `azd down` before run `azd pipeline config`, it has been mentioned [here](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/use-terraform-for-azd#azd-pipeline-config-for-terraform). I missed it before. Please ignore my ideal test step @v-xuto @Menghua1

**Comment by fangjian0423** [comment]
Close it because the issue has been fixed.

**Comment by v-xuto** [comment]
@fangjian0423 Please add relevant hints in `README`: Before executing `azd pipeline config`, need to execute `azd down` and enable remote state according to the [document](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/use-terraform-for-azd#azd-pipeline-config-for-terraform).
